# Output configuration ─────────────────────────────────────────────────────────

[output:DP-1]
mode = 1920x1080@164917
position = 0,0
transform = normal
scale = 1.000000

# You can get the names of your outputs with wlr-randr.

# Core options ─────────────────────────────────────────────────────────────────

[core]

# List of plugins to be enabled.
# See the Configuration document for a complete list.
plugins = \
  alpha \
  animate \
  autostart \
  command \
  follow-focus \
  fast-switcher \
  foreign-toplevel \
  grid \
  gtk-shell \
  idle \
  invert \
  matcher \
  move \
  oswitch \
  place \
  resize \
  shortcuts-inhibit \
  simple-tile \
  switcher \
  vswitch \
  wayfire-shell \
  wm-actions \
  zoom \
  blur

# Close focused window.
close_top_view = <shift> <alt> KEY_C

# Workspaces arranged into a grid: 3 × 3.
vwidth = 10
vheight = 1

[simple-tile]
tile_by_default = any

[idle]
screensaver_timeout = -1
dpms_timeout = -1

# Startup commands ─────────────────────────────────────────────────────────────

[autostart]

background = wbg ~/Pictures/Desktop/zeckma-banner-update1-prog1.png

# XDG desktop portal
# Needed by some GTK applications
portal = /usr/libexec/xdg-desktop-portal

# Applications ─────────────────────────────────────────────────────────────────

[command]

binding_terminal = <shift> <alt> KEY_ENTER
command_terminal = foot

binding_launcher = <super> KEY_SPACE
command_launcher = rofi -show drun

binding_browser = <shift> <alt> KEY_F
command_browser = firefox

binding_screenshot = <ctrl> <alt> KEY_MINUS
command_screenshot = take_screenshot

# Follow Focus ─────────────────────────────────────────────────────────────────

[follow-focus]
focus_delay = 0
threshold = 0

# Workspaces ───────────────────────────────────────────────────────────────────

[vswitch]
gap = 0
duration = 500
binding_1 = <super> KEY_1
binding_2 = <super> KEY_2
binding_3 = <super> KEY_3
binding_4 = <super> KEY_4
binding_5 = <super> KEY_5
binding_6 = <super> KEY_6
binding_7 = <super> KEY_7
binding_8 = <super> KEY_8
binding_9 = <super> KEY_9
binding_10 = <super> KEY_0
with_win_1 = <shift> <alt> KEY_1
with_win_2 = <shift> <alt> KEY_2
with_win_3 = <shift> <alt> KEY_3
with_win_4 = <shift> <alt> KEY_4
with_win_5 = <shift> <alt> KEY_5
with_win_6 = <shift> <alt> KEY_6
with_win_7 = <shift> <alt> KEY_7
with_win_8 = <shift> <alt> KEY_8
with_win_9 = <shift> <alt> KEY_9
with_win_10 = <shift> <alt> KEY_0
